spring:
  datasource:
    mysql:
      url: jdbc:mysql://10.147.245.41:3306/chaos?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Zmzzmz010627!
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 10.147.245.41
    port: 6379
    password: Zmzzmz010627!
    database: 0
  rabbitmq:
    host: 10.147.245.41
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: 10.147.245.41         # MongoDB服务器地址
      port: 27017               # MongoDB服务器端口
      database: admin   # MongoDB数据库名称
      username: root   # MongoDB用户名（如果启用了身份验证）
      password: Zmzzmz010627!   # MongoDB密码（如果启用了身份验证）
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除字段值
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值
server:
  port: 8002
  servlet:
    context-path: /api
  tomcat:
    additional-tld-skip-patterns: X-Content-Type-Options
    max-threads: 2000
    max-connections: 1000
chaos:
  mesh:
    url: http://10.147.71.27:30854
    token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlI1dE9lNTItQmxyMXFqWVRSUlpQTUlCN3BNWWc3R0szWnIxeFU2UVEtSDQifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzcyNzIyMjY0LCJpYXQiOjE3NDExODYyNjQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6IiwidWlkIjoiZTBjZmIzZmMtNWRlNS00NDY2LWJlYzctMjM1OTgyOWVlNWVjIn19LCJuYmYiOjE3NDExODYyNjQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6In0.PPYNYB3P2QJOBkjKXn0hSIQMKUeH7bZlJNydOzVjQDGRFp1U11SId7j8uDuwz4DCkWp4Jup1bW_vwUVH_z_VWtkBGvLsx2H0tPgMpv2QhUD5diNKbVhQ4wt11YM8rACUR9jXjJt7Shzyeh3av8PxHnf3W2M7ED7Xt9hEJFRNxsmk17qKf15rCbHg3ANEXnYtGgwvQO2qElrTQ8hf54Fw4VGpu_yEci-9t-6XlB9V3TrgBwZrbiDN78WOeODldb5eDAYsU4sqHyG-0zqAc5He-SMUciela9QMGxTA2WA_WMLJ_wHg2yI5gM1g69KUPF7kVTN_I0vNaMobial2NFu3ZA
prometheus:
  url: http://10.147.71.27:8004/api/v1/query_range
  os-type: ubuntu
autoTest:
  url: http://10.147.245.34:8080
platform:
  name: cmp
  workflowaddr: chaos-test
coroot:
  url: http://10.147.71.27:8003/api/project/
  projectId: hg7c03k5
  cookie: coroot_session=eyJpZCI6MX0=.sYH_NdIl_L9utOToixZg7cTLPxVnGjrS5vAbC5C8niE=
file:
  upload-dir: /data/mj/apache-tomcat-9.0.93/webapps/loadscripts
#  upload-dir: /Users/mj/study/ISCS/apache-tomcat-9.0.93/webapps/loadscripts

kubernetes:
  api-url: https://10.147.71.27:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlI1dE9lNTItQmxyMXFqWVRSUlpQTUlCN3BNWWc3R0szWnIxeFU2UVEtSDQifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzcyNzIyMjY0LCJpYXQiOjE3NDExODYyNjQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6IiwidWlkIjoiZTBjZmIzZmMtNWRlNS00NDY2LWJlYzctMjM1OTgyOWVlNWVjIn19LCJuYmYiOjE3NDExODYyNjQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6In0.PPYNYB3P2QJOBkjKXn0hSIQMKUeH7bZlJNydOzVjQDGRFp1U11SId7j8uDuwz4DCkWp4Jup1bW_vwUVH_z_VWtkBGvLsx2H0tPgMpv2QhUD5diNKbVhQ4wt11YM8rACUR9jXjJt7Shzyeh3av8PxHnf3W2M7ED7Xt9hEJFRNxsmk17qKf15rCbHg3ANEXnYtGgwvQO2qElrTQ8hf54Fw4VGpu_yEci-9t-6XlB9V3TrgBwZrbiDN78WOeODldb5eDAYsU4sqHyG-0zqAc5He-SMUciela9QMGxTA2WA_WMLJ_wHg2yI5gM1g69KUPF7kVTN_I0vNaMobial2NFu3ZA
  verify-ssl: false

loadtestservicelist:
  loadScriptUrl: http://10.147.245.41:8001/loadscripts/
  runTest:
    url: http://10.147.245.27:6666/api/load/run/{loadId}
    #    url: http://localhost:6666/api/load/run/{loadId}
    method: POST
  stopTest:
    url: http://10.147.245.27:6666/api/load/stop/{loadId}
    #    url: http://localhost:6666/api/load/stop/{loadId}
    method: POST