spring:
  datasource:
    mysql:
      url: jdbc:mysql://116.63.51.45:3306/chaos?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Zmzzmz010627!
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 116.63.51.45
    port: 6379
    password: Zmzzmz010627!
    database: 0
  rabbitmq:
    host: 116.63.51.45
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: 116.63.51.45         # MongoDB服务器地址
      port: 27017               # MongoDB服务器端口
      database: admin   # MongoDB数据库名称
      username: root   # MongoDB用户名（如果启用了身份验证）
      password: Zmzzmz010627!   # MongoDB密码（如果启用了身份验证）
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除字段值
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值
server:
  port: 8002
  servlet:
    context-path: /api
  tomcat:
    additional-tld-skip-patterns: X-Content-Type-Options
    max-threads: 2000
    max-connections: 1000
chaos:
  mesh:
    url: http://116.63.51.45:30854
    token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImctR3o3S2JGU2RQWUN6bzZac2tvOVcxb0lNWHkzOGdnR29jTWZtRjB3aWcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzczNDE2NzExLCJpYXQiOjE3NDE4ODA3MTEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6IiwidWlkIjoiZjcwYjJhODEtMjNmNy00Y2YyLWJhNjMtNjk1NDBhN2I2Yzk0In19LCJuYmYiOjE3NDE4ODA3MTEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6In0.gqryPjgClH5K6EecX6Gx8J6tLnkuPgZanqFsZGoDQxPJp4AzuTjKYtp5xWsw-2dU7G54f_qL7sLraXhmu2mCS-Sbyzo9CpGifZBpZmouA0v4wk28-HMMPkxJnM_UV3kH1PGrcSVd8L_OgJ4Oq1d-yqY7cGdqB-DgOf-G7JQB9IfcjKw6no5NVE4j8i_DGhNIJ5IsXu6Qyo10SvP7rTzC9ke71ma3ujqxvov1V0INsmog5eVwgynlNRoz389YoUM3-iGCYE-R23VwmAkXCDZCBXuR6d3zH0iNionCjLQStWBEhqRZK8DFQ78r9eSZ5Y5gt3mDmZxqoG_EWFRaIGvp3w
prometheus:
  url: http://116.63.51.45:8004/api/v1/query_range
  os-type: ubuntu
autoTest:
  url: http://116.63.51.45:8080
platform:
  name: cmp
  workflowaddr: chaos-test
coroot:
  url: http://116.63.51.45:8003/api/project/
  projectId: mjrbub1h
  cookie: coroot_session=eyJpZCI6MX0=.gNsIPWsHNJxvA0tv0RLH1J8rK1TiwjDdjL03ANHoQCQ=
file:
  upload-dir: /data/mj/apache-tomcat-9.0.93/webapps/loadscripts
#  upload-dir: /Users/mj/study/ISCS/apache-tomcat-9.0.93/webapps/loadscripts

kubernetes:
  api-url: https://116.63.51.45:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImctR3o3S2JGU2RQWUN6bzZac2tvOVcxb0lNWHkzOGdnR29jTWZtRjB3aWcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzczNDE2NzExLCJpYXQiOjE3NDE4ODA3MTEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6IiwidWlkIjoiZjcwYjJhODEtMjNmNy00Y2YyLWJhNjMtNjk1NDBhN2I2Yzk0In19LCJuYmYiOjE3NDE4ODA3MTEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6In0.gqryPjgClH5K6EecX6Gx8J6tLnkuPgZanqFsZGoDQxPJp4AzuTjKYtp5xWsw-2dU7G54f_qL7sLraXhmu2mCS-Sbyzo9CpGifZBpZmouA0v4wk28-HMMPkxJnM_UV3kH1PGrcSVd8L_OgJ4Oq1d-yqY7cGdqB-DgOf-G7JQB9IfcjKw6no5NVE4j8i_DGhNIJ5IsXu6Qyo10SvP7rTzC9ke71ma3ujqxvov1V0INsmog5eVwgynlNRoz389YoUM3-iGCYE-R23VwmAkXCDZCBXuR6d3zH0iNionCjLQStWBEhqRZK8DFQ78r9eSZ5Y5gt3mDmZxqoG_EWFRaIGvp3w
  verify-ssl: false

loadtestservicelist:
  loadScriptUrl: http://116.63.51.45:8080/loadscripts/
  runTest:
    url: http://1.94.151.57:6666/api/load/run/{loadId}
    #    url: http://localhost:6666/api/load/run/{loadId}
    method: POST
  stopTest:
    url: http://1.94.151.57:6666/api/load/stop/{loadId}
    #    url: http://localhost:6666/api/load/stop/{loadId}
    method: POST