spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/chaos?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Zmzzmz010627!
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    password: Zmzzmz010627!
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost        # MongoDB服务器地址
      port: 27017               # MongoDB服务器端口
      database: admin   # MongoDB数据库名称
      username: root   # MongoDB用户名（如果启用了身份验证）
      password: Zmzzmz010627!   # MongoDB密码（如果启用了身份验证）
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除字段值
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值
server:
  port: 8888
  servlet:
    context-path: /api
  tomcat:
    additional-tld-skip-patterns: X-Content-Type-Options
    max-threads: 2000
    max-connections: 1000
chaos:
  mesh:
    url: http://10.147.245.34:30854
    token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imczbkt1SWhUNlpZOGwxYXFaTEZqUVBfd0JYNWdSM2laanFaUk5BTXZoZlUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzcyMDkwMDY3LCJpYXQiOjE3NDA1NTQwNjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6IiwidWlkIjoiYmZiYjQ4YzMtNWZmMS00Mjk4LTgwZTYtMDNjMzllYzU0MDk2In19LCJuYmYiOjE3NDA1NTQwNjcsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6In0.UhUp8AzWftYrdsq4JOXEVp8z6-REN5N-JyyvlzajQmQFIu9Q0C7QW2SQlsFjecPeY631JTofiYloHTrOZHxe-mMZ9K_21WG0pEP2l0Rj1K9poIg6LABb7s8GcbN1jR8RQl326L3q0enbV0SrAIzwLDm5DCXelhuck-yWUAoLZrtqKflkfv9WYN3xPXTIvVfzO07HS6OEaznLyGfwNTs5d7duBUN6ojKbYnTk5ksZFxAT3XIu5Cz2NUl18FzZss-lDyD_4N5Bp2_PDpfHSukdhpbkpnNtk84b0d5jj_I0AUVvyJndM5Q-Kdy9T1PdeIEksoYOZB6w5savddd_L1eg9g
prometheus:
  url: http://10.147.245.34:8004/api/v1/query_range
  os-type: ubuntu
autoTest:
  url: http://10.147.245.34:8080
platform:
  name: cmp
  workflowaddr: chaos-test
coroot:
  url: http://10.147.245.34:8003/api/project/
  projectId: 75xsw0c2
  cookie: coroot_session=eyJpZCI6MX0=.6gsYttzTNxFwxgVocwllLwkjRDclTqOKrKAVjvTEu4o=
file:
  upload-dir: /data/mj/apache-tomcat-9.0.93/webapps/loadscripts
#  upload-dir: /Users/mj/study/ISCS/apache-tomcat-9.0.93/webapps/loadscripts

kubernetes:
  api-url: https://10.147.245.34:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Imczbkt1SWhUNlpZOGwxYXFaTEZqUVBfd0JYNWdSM2laanFaUk5BTXZoZlUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzcyMDkwMDY3LCJpYXQiOjE3NDA1NTQwNjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6IiwidWlkIjoiYmZiYjQ4YzMtNWZmMS00Mjk4LTgwZTYtMDNjMzllYzU0MDk2In19LCJuYmYiOjE3NDA1NTQwNjcsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFjY291bnQtY2x1c3Rlci1tYW5hZ2VyLWRwcmd6In0.UhUp8AzWftYrdsq4JOXEVp8z6-REN5N-JyyvlzajQmQFIu9Q0C7QW2SQlsFjecPeY631JTofiYloHTrOZHxe-mMZ9K_21WG0pEP2l0Rj1K9poIg6LABb7s8GcbN1jR8RQl326L3q0enbV0SrAIzwLDm5DCXelhuck-yWUAoLZrtqKflkfv9WYN3xPXTIvVfzO07HS6OEaznLyGfwNTs5d7duBUN6ojKbYnTk5ksZFxAT3XIu5Cz2NUl18FzZss-lDyD_4N5Bp2_PDpfHSukdhpbkpnNtk84b0d5jj_I0AUVvyJndM5Q-Kdy9T1PdeIEksoYOZB6w5savddd_L1eg9g
  verify-ssl: false

loadtestservicelist:
  loadScriptUrl: http://10.147.245.41:8001/loadscripts/
  runTest:
    url: http://10.147.245.27:6666/api/load/run/{loadId}
    #    url: http://localhost:6666/api/load/run/{loadId}
    method: POST
  stopTest:
    url: http://10.147.245.27:6666/api/load/stop/{loadId}
    #    url: http://localhost:6666/api/load/stop/{loadId}
    method: POST